@startjson
{
"quizWords": {
      "-NLXDY6XUoi5Pchvs5ZZ": {
        "-NLXDY6XUoi5Pchvs5Z_": {
          "id": "-NLXDY6XUoi5Pchvs5Z_",
          "learned": true,
          "quizItemId": "-NLXDY6XUoi5Pchvs5ZZ",
          "repeat": 3,
          "translation": "dog",
          "word": "pies"
        },
        "-NLXDY6XUoi5Pchvs5Za": "word data",
        "-NLXDY6YYa0Y5r_165CD": "word data",
        "-NLXDY6YYa0Y5r_165CE": "word data"
      },
      "-NLXDY6XUoi5Pchvs5ZZ2": "quiz words",
      "-NLXDY6XUoi5Pchvs5ZZ3": "quiz words"
    }
}
@endjson