@startjson
{
"quizzes": {
      "zxcasd": {
        "completedWords": 1,
        "id": "-NLXDY6XUoi5Pchvs5ZZ",
        "mode": "Classic",
        "name": "Animals",
        "wordsNumber": 4
      },
      "zxcasd2":"quiz data",
      "zxcasd3":"quiz data"
    }
}
@endjson