@startjson
{
"quizWords": {
      "zxcasd": {
        "qweasd": {
          "id": "-NLXDY6XUoi5Pchvs5Z_",
          "learned": true,
          "quizItemId": "zxcasd",
          "repeat": 3,
          "translation": "dog",
          "word": "pies"
        },
        "qweasd2": "word data",
        "qweasd3": "word data"
      },
      "zxcasd2": "quiz words",
      "zxcasd3": "quiz words"
    }
}
@endjson